# g4_moves_cfg.py v1.1 (2026-10-10) — 4기 동작 짝 표: 인물 → 시트 칸 · 움짤 장 → 게임 동작 (tools/g4_moves.py 가 읽음)
#  v1.1: 드라이브 폴더 이름 · 도감 등급 반영 (기병기사 4성 (도감) · 챔피언 2성급 · 유니 2성 NPC/포획 · 콘 포획/영입 · 각펄 2성) · 세르파 자원 유닛 수정 거품게 (crab) · sk 시트 배율 손보정 (머리 크기 대조 — 유니 B · 콘 B/M · 기병기사 A · 친칠라 G/A · 망향 E/F/A · 장끌레도르 B/C/D) · 리완 C 기준 1.1 · 마계장군 low 뒤집음 · 분홍 마족 B/C 기준 0.87 · 펄 · 각펄 움짤 배율 scale_by='idle' + ak (머리 크기 비교)
#  v1.0: 처음
#  · 시트 이름은 자른 칸 폴더 (드라이브 '1010 4기 업뎃' 폴더/시트 이름), 칸은 r<줄>c<칸> (tools/g4_cut.py)
#  · P[동작] = [(시트 별명, [칸 …])] — 여러 장이면 순서대로 띠 (발 맞춤). '!칸' = 좌우 뒤집어 씀 (그 칸만 반대쪽을 봄)
#  · refs: 시트 배율 기준 칸 {별명: [(칸, 키 비율)]} — 없으면 그 시트에서 서 있는 · 걷는 동작 칸으로 (RATIO)
#  · A[동작] = (움짤 파일, 시작 장, 끝 장, 몇 장, 'fix' | 'track', 재생 {fps, once}) — 움짤 배율은 scale_by='idle' (대기 움짤 몸 키 × ak[동작]) 또는 aref (기준 장, 키 비율)
#  · new: 새 노트 (art/h2/notes/<slug>.json) 를 만듦 — idle 칸이 노트 대기 그림, portrait (원화) · face (대기 칸 머리)
W5 = ['r0c0', 'r0c1', 'r0c2', 'r0c3', 'r0c4']
W4 = ['r0c0', 'r0c1', 'r0c2', 'r0c3']
DATE = '2026-10-10'; BATCH = "4기 1차 (드라이브 '1010 4기 업뎃')"

CFG = {
  # ───────── 새 인물 ─────────
  'yuni': dict(new=dict(name='오니 유니', rank='2성', role='NPC·적 (포획 가능)', tall=1.72, weight=58, tag='demon', role_job='돌격', bag=3,
                        apt=dict(melee=4, spear=1, bow=0, gun=0, magic=2, stealth=3), portrait='유니/오니 유니 기본 원화.png', codex=None,
                        desc='보석 뿔을 단 유카타 차림 오니 (2성). NPC 로 먼저 만나고, 적으로 붙으면 포획할 수 있음 (드라이브 폴더 "유니(2성 NPC&포획가능 적 오니"). 손톱으로 할퀴고 덮침'),
    S=dict(A='유니/10종 캐릭터 워크·런 사이클 시트', B='유니/보석 오니 전투 포즈 스프라이트 시트', C='유니/보석 오니의 10포즈 액션 스프라이트', D='유니/보석 오니의 다섯 가지 전신 포즈', E='유니/보석 오니의 다섯 가지 포즈'),
    idle=('D', 'r0c4'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1', 'r1c2', 'r1c3'])], ready=[('B', ['r1c3'])], windup=[('B', ['r0c0'])], attack=[('B', ['r0c1'])], attack2=[('B', ['r1c4'])],
           hurt=[('B', ['r0c2'])], down=[('B', ['r0c3'])], kneel=[('B', ['r0c4'])], rest=[('B', ['r1c0'])], rest2=[('B', ['r1c1'])], taunt=[('D', ['r0c1'])], charm=[('E', ['r0c3'])],
           walk2=[('C', W5)], dash=[('C', ['r1c0', 'r1c1', 'r1c2'])], idle2=[('E', ['r0c0'])]),
    refs=dict(D=[('r0c4', 1.0)], E=[('r0c0', 1.0)]), sk=dict(B=0.645)),
  'kon': dict(new=dict(name='도살자 콘', rank='2성', role='적 (포획 · 영입 가능)', tall=1.74, weight=62, tag='human', role_job='돌격', bag=3,
                       apt=dict(melee=4, spear=1, bow=0, gun=0, magic=0, stealth=4), portrait='도살자콘/도살자 콘 원화 기본.png', codex=None,
                       desc='뼈 문신 · 붉은 누더기 털망토의 단검 도살자 (2성). 적으로 만나 포획 · 영입할 수 있음. 쓰러진 적을 끝장냄'),
    S=dict(A='도살자콘/공중에서 반대 보폭을 취한 해골 전사', B='도살자콘/붉은 눈 해골 전사 스프라이트', C='도살자콘/붉은 눈의 해골 전사 스프라이트', D='도살자콘/뼈 문신 단검 여성의 다섯 포즈',
           E='도살자콘/뼈 문신 전사의 다섯 전투 포즈', F='도살자콘/뼈 문신 전사의 다섯 포즈', G='도살자콘/뼈문신 전사의 10가지 전투 포즈', H='도살자콘/해골 문신 도살자의 10가지 전투 포즈',
           I='도살자콘/해골 문신 여성의 다섯 포즈', J='도살자콘/해골 문신 전사의 5연속 전투 스프라이트', K='도살자콘/해골 문신 전사의 5포즈 스프라이트', L='도살자콘/해골 문신 전사의 다섯 특수 자세',
           M='도살자콘/해골 문신 전사의 단검 자세 4종', N='도살자콘/해골 전사의 걷기 포즈 시트'),
    idle=('D', 'r0c0'),
    P=dict(walk=[('N', ['r0c0', 'r0c1', 'r0c2', 'r1c0', 'r1c1'])], run=[('J', ['r0c0', 'r0c1'])], windup=[('J', ['r0c2'])], attack=[('J', ['r1c0', 'r1c1'])],
           attack2=[('I', ['r0c0', 'r0c1'])], ready=[('B', ['r1c1'])], hurt=[('E', ['r0c2'])], hurt2=[('H', ['r0c2'])], down=[('E', ['r1c0'])], dead=[('H', ['r1c0'])], kneel=[('E', ['r1c1'])],
           low=[('D', ['r1c0'])], crouch=[('I', ['r0c2'])], special=[('H', ['r0c1', 'r3c0'])], dash=[('L', ['r0c0'])], rest=[('B', ['r0c1'])], sit=[('M', ['r0c1'])],
           taunt=[('D', ['r0c1'])], idle2=[('I', ['r1c3'])], combo=[('A', ['r0c2', 'r1c0', 'r1c1'])], combo2=[('C', ['r0c2', 'r1c0', 'r1c1'])], walk2=[('K', ['r0c1', 'r1c0', 'r1c1'])]),
    refs=dict(N=[('r0c0', 0.98)], J=[('r1c1', 0.9)], A=[('r1c1', 0.9)], C=[('r1c1', 0.9)], I=[('r1c1', 1.0)], E=[('r0c0', 0.9)], H=[('r2c1', 0.74)], B=[('r1c0', 0.92)], L=[('r0c1', 1.0)],
              M=[('r1c1', 0.95)], K=[('r0c0', 1.0)], D=[('r0c0', 1.0)]), sk=dict(B=0.77, M=0.77)),
  'riwan': dict(new=dict(name='리완', rank='4성', role='동료', tall=1.76, weight=95, tag='knight', role_job='방패', bag=4,
                         apt=dict(melee=4, spear=1, bow=0, gun=0, magic=1, stealth=0), portrait='4기/리완 원화.png', codex=None,
                         desc='4성 탱커. 철퇴와 큰 수정 방패의 기사. 앞을 막고 버팀'),
    S=dict(A='리완/수정 방패 기사 10종 포즈 시트', B='리완/수정 방패 기사 10포즈 스프라이트 시트', C='리완/수정 방패 기사, 다섯 가지 포즈', D='리완/수정 방패 기사, 다섯 포즈',
           E='리완/수정 방패 기사의 여섯 가지 전투 동작', F='리완/흰 캔버스의 10인 전신 스프라이트 배열'),
    idle=('A', 'r1c2'),
    P=dict(walk=[('F', W5)], run=[('F', ['r1c0', 'r1c1'])], windup=[('F', ['r1c2'])], attack=[('F', ['r1c3'])], attack2=[('F', ['r1c4'])], ready=[('A', ['r0c0'])],
           slam=[('A', ['r0c1'])], hurt=[('A', ['r0c2'])], down=[('A', ['r0c3'])], kneel=[('A', ['r0c4'])], rest=[('A', ['r1c0'])], rest2=[('A', ['r1c1'])], low=[('A', ['r1c4'])],
           guard=[('C', ['r0c2'])], guard2=[('C', ['r1c1'])], shoulder=[('C', ['r0c1'])], kick=[('B', ['r1c3'])], walk2=[('E', ['r0c1', 'r0c2', 'r1c0'])], run2=[('E', ['r1c1', 'r1c2'])]),
    refs=dict(A=[('r1c2', 1.0)], F=[('r0c0', 0.98)], B=[('r0c0', 0.98)], C=[('r0c0', 1.1)], D=[('r0c0', 1.0)], E=[('r0c0', 1.0)])),
  'serpa': dict(new=dict(name='세르파', rank='3성', role='동료', tall=1.62, weight=48, tag='construct', role_job='소환', bag=3,
                         apt=dict(melee=2, spear=0, bow=0, gun=0, magic=4, stealth=1), portrait='세르파/세르파 기본.png', codex=None,
                         desc='3성 몬스터퀸. 마도공학 광물계 정령왕 코어. 광석생물 · 시종을 불러 물량으로 싸움'),
    S=dict(A='세르파/반대 보폭의 게임 캐릭터 걷기 포즈', B='세르파/세르파 - 뛰기+기술', C='세르파/세르파 안드로이드 5포즈 시트', D='세르파/세르파 안드로이드 전투 포즈 시트',
           E='세르파/세르파 안드로이드의 5가지 전투 자세', F='세르파/세르파 지원 안드로이드 4포즈 시트', G='세르파/세르파 지원 안드로이드 포즈 시트', H='세르파/수정 왕관의 지원 안드로이드 스프라이트'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', ['r0c1', 'r0c2', 'r1c0', 'r1c1'])], run=[('B', ['r0c0', 'r0c1'])], cast=[('B', ['r0c2'])], skill=[('B', ['r1c0', 'r1c1'])], summon=[('C', ['r0c2'])],
           kneel2=[('C', ['r0c0'])], taunt=[('C', ['r0c1'])], rest=[('C', ['r1c0'])], idle2=[('C', ['r1c1'])], ready=[('E', ['r0c0'])], command=[('E', ['r0c1'])],
           hurt=[('E', ['r0c2'])], down=[('E', ['r1c0'])], kneel=[('E', ['r1c1'])], rest2=[('F', ['r0c0'])], guard=[('F', ['r1c0'])], push=[('F', ['r1c1'])],
           jump=[('G', ['r0c0'])], wave=[('G', ['r1c0'])], walk2=[('H', ['r0c1', 'r1c0'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 0.9)], C=[('r1c1', 1.0)], E=[('r0c2', 0.95)], F=[('r1c1', 0.9)], G=[('r0c1', 1.0)], H=[('r0c0', 1.0)])),
  'shu': dict(new=dict(name='슈', rank='3성', role='동료', tall=1.66, weight=50, tag='spirit', role_job='치유', bag=3,
                       apt=dict(melee=2, spear=0, bow=0, gun=0, magic=4, stealth=2), portrait='4기/슈 스탠딩2.png', codex=None,
                       desc='3성 힐러. 정령계 인간 — 대기를 마시며 삶. 눈을 가린 메이드 치유사, 빈손으로 지킴'),
    S=dict(A='슈/게임 캐릭터 반대 걸음 포즈', B='슈/눈가리개 치유사 슈의 특별 포즈 5종', C='슈/눈가리개 치유사의 5가지 전투 포즈', D='슈/눈가린 치유사 슈 5포즈 스프라이트',
           E='슈/눈가린 치유사의 공중 역보폭', F='슈/맹목의 치유사 5포즈 스프라이트 시트', G='슈/빈손으로 지키는 치유사', H='슈/치유사 슈의 다섯 포즈 시트'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', ['r0c1', 'r0c2', 'r1c0', 'r1c1'])], run=[('C', ['r0c0', 'r0c1'])], cast=[('C', ['r0c2'])], skill=[('C', ['r1c0'])], heal=[('B', ['r0c0'])], reach=[('C', ['r1c1'])],
           ready=[('F', ['r0c0'])], guard=[('F', ['r0c1'])], hurt=[('F', ['r0c2'])], down=[('F', ['r1c0'])], kneel=[('F', ['r1c1'])], hurt2=[('G', ['r1c0'])], attack=[('G', ['r1c1'])],
           rest=[('B', ['r0c1'])], rest2=[('G', ['r0c1'])], idle2=[('B', ['r1c0'])], taunt=[('H', ['r0c1'])], jump=[('H', ['r0c0'])], wave=[('B', ['r0c2'])], run2=[('E', ['r0c0', 'r0c1'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r1c0', 1.0)], C=[('r0c0', 0.9)], E=[('r0c0', 0.9)], F=[('r0c0', 0.95)], G=[('r1c1', 0.9)], H=[('r1c1', 1.0)])),
  'glitch': dict(new=dict(name='글리치 챔피언', rank='2성', role='적', tall=1.95, weight=120, tag='knight', role_job='선봉', bag=4,
                          apt=dict(melee=5, spear=2, bow=0, gun=0, magic=1, stealth=0), portrait='챔피언/글리치 챔피언 원화.png', codex=None,
                          desc='30층 스타디움의 챔피언 — 2성급이지만 오로지 기술만으로 승부하는 30층의 최강자. 황금 갑옷 검투사, 갑옷 위로 화면이 깨지듯 빛이 튐 (글리치)'),
    S=dict(A='챔피언/5×2 배열의 10인 전신 스프라이트', B='챔피언/금빛 기사 다섯 가지 전투 자세', C='챔피언/금빛 전사의 10포즈 전투 스프라이트', D='챔피언/황금 갑옷 전사의 10가지 전투 포즈',
           E='챔피언/황금 갑옷 전사의 다섯 전투 자세'),
    idle=('C', 'r0c0'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1'])], windup=[('A', ['r1c2'])], attack=[('A', ['r1c3'])], attack2=[('A', ['r1c4'])], hurt=[('D', ['r0c2'])], down=[('D', ['r1c0'])],
           kneel=[('D', ['r1c1'])], rest=[('D', ['r1c2'])], guard=[('D', ['r2c1'])], leap=[('D', ['r2c2', 'r3c0'])], dash=[('E', ['r0c0'])], bash=[('E', ['r0c1'])], low=[('E', ['r1c1'])],
           slam=[('E', ['r1c0'])], thrust=[('B', ['r0c2'])], lunge=[('B', ['r0c1'])], slash=[('B', ['r0c0', 'r1c0'])], walk2=[('C', ['r0c2', 'r1c0', 'r1c1'])]),
    refs=dict(A=[('r0c0', 0.98)], C=[('r0c0', 1.0)], D=[('r0c2', 0.92)], E=[('r1c2', 0.95)], B=[('r1c0', 0.9)])),
  'nurse': dict(new=dict(name='간호사', rank='1성', role='동료', tall=1.55, weight=44, tag='human', role_job='치유', bag=3,
                         apt=dict(melee=1, spear=0, bow=0, gun=2, magic=1, stealth=2), portrait='@codex:img/char/nurse_art.webp', codex='nurse',
                         desc='인간계의 낙오자 — 오래전 전쟁터에서 죽어서 온 젊은 간호사. 치료 · 버프 특화, 전투는 거의 못함'),
    S=dict(A='4기/간호사1', B='4기/간호사특수2'),
    idle=('B', 'r1c0'),
    P=dict(walk=[('A', W4)], run=[('A', ['r0c4', 'r1c0'])], attack=[('B', ['r1c1'])], guard=[('B', ['r1c2'])], heal=[('B', ['r0c3'])], hurt=[('A', ['r1c1'])], stun=[('A', ['r1c2'])],
           hurt2=[('A', ['r1c3'])], kneel=[('A', ['r1c4'])], down=[('B', ['r0c2'])], rest=[('B', ['r0c0'])], rest2=[('B', ['r0c1'])]),
    refs=dict(A=[('r0c0', 0.98)], B=[('r1c0', 1.0)])),
  'darkrider': dict(new=dict(name='기병기사', rank='4성', role='적', tall=2.7, weight=650, tag='knight', role_job='돌격', bag=4,
                             apt=dict(melee=4, spear=3, bow=0, gun=0, magic=1, stealth=0), portrait='4기/기병기사(3성정도).png', codex='darkrider',
                             desc='유령 군마를 탄 암흑 기사 (드라이브 파일 이름은 3성 정도 · 도감 등급 4). 길게 돌진하며 베고 짓밟음'),
    S=dict(A='추가스프라이트/암흑 기사와 청록 갑마의 10가지 동작', B='추가스프라이트/유령 군마 기사 10포즈 스프라이트 시트'),
    idle=('B', 'r1c2'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1'])], windup=[('A', ['r1c2'])], attack=[('A', ['r1c3'])], attack2=[('A', ['r1c4'])], rear=[('B', ['r0c0'])],
           slash=[('B', ['r0c1'])], low=[('B', ['r0c2'])], down=[('B', ['r0c3'])], rest=[('B', ['r0c4'])], kneel=[('B', ['r1c0'])], dead=[('B', ['r1c1'])], thrust=[('B', ['r1c3'])], swing=[('B', ['r1c4'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r1c2', 1.0)]), sk=dict(A=1.3)),
  'sawknight': dict(new=dict(name='마계장군 A', rank='3성', role='적', tall=2.05, weight=140, tag='demon', role_job='선봉', bag=4,
                             apt=dict(melee=5, spear=1, bow=0, gun=0, magic=1, stealth=0), portrait='4기/마계장군A.png', codex='X-demonkin2',
                             desc='마계의 장군직 (3성 정도). 톱날 대검을 든 망토 기사'),
    S=dict(A='추가스프라이트/거대한 대검의 악령 기사 스프라이트', B='추가스프라이트/열 가지 포즈의 악마 기사 스프라이트', C='추가스프라이트/해골 기사 대검 공격 스프라이트 시트'),
    idle=('B', 'r1c2'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1'])], windup=[('A', ['r1c2'])], attack=[('A', ['r1c3'])], attack2=[('A', ['r1c4'])], low=[('B', ['!r0c0'])], lift=[('B', ['r0c1'])],
           hurt=[('B', ['r0c2'])], down=[('B', ['r0c3'])], kneel=[('B', ['r0c4'])], idle2=[('B', ['r1c0'])], rest=[('B', ['r1c1'])], leap=[('B', ['r1c4'])],
           slam=[('C', ['r0c0', 'r0c1'])], thrust=[('C', ['r0c2'])], lunge=[('C', ['r1c0'])], jumpslash=[('C', ['r1c1'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r1c2', 1.0)], C=[('r0c0', 0.95)])),
  'purpledemon': dict(new=dict(name='보라 날개 악마', rank='3성', role='적', tall=1.85, weight=60, tag='demon', role_job='돌격', bag=3,
                               apt=dict(melee=4, spear=0, bow=0, gun=0, magic=2, stealth=3), portrait=None, codex=None,
                               desc='박쥐 날개 · 흰 무늬 보라 악마. 날개로 덮치고 발톱으로 할큄'),
    S=dict(A='추가스프라이트/보라색 악마 10종 액션 스프라이트 시트', B='추가스프라이트/보라색 악마의 8가지 전투 포즈'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', W4)], run=[('A', ['r0c4', 'r1c0'])], hurt=[('A', ['r1c1'])], guard=[('A', ['r1c2'])], stance=[('A', ['r1c3'])], down=[('A', ['r1c4'])],
           ready=[('B', ['r0c0'])], attack=[('B', ['r0c1'])], attack2=[('B', ['r0c2'])], kick=[('B', ['r0c3'])], leap=[('B', ['r1c0'])], low=[('B', ['r1c1'])], cast=[('B', ['r1c2'])], kick2=[('B', ['r1c3'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 0.8)])),
  'pinkdemon': dict(new=dict(name='분홍 마족', rank='3성', role='적', tall=1.8, weight=55, tag='demon', role_job='마법', bag=3,
                             apt=dict(melee=2, spear=0, bow=0, gun=0, magic=5, stealth=2), portrait=None, codex=None,
                             desc='가시 바퀴 후광 · 꼬리 · 분홍 소용돌이 무늬의 마족. 손의 마력 구슬로 쏘고 밀침'),
    S=dict(A='추가스프라이트/분홍 마족 10포즈 스프라이트 시트', B='추가스프라이트/분홍 악마의 10포즈 스프라이트 시트', C='추가스프라이트/열 가지 전투 포즈 시트'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1'])], cast=[('A', ['r1c2'])], attack=[('A', ['r1c3'])], attack2=[('A', ['r1c4'])], summon=[('C', ['r0c0'])], claw=[('C', ['r0c1'])],
           hurt=[('C', ['r0c2'])], ready=[('C', ['r0c3'])], hurt2=[('C', ['r0c4'])], down=[('C', ['r1c0'])], kneel=[('C', ['r1c1'])], rest=[('C', ['r1c3'])]),
    refs=dict(A=[('r0c0', 1.0)], C=[('r0c3', 0.87)], B=[('r0c3', 0.87)])),
  'regina': dict(new=dict(name='레지나', rank='5성', role='보스', tall=1.9, weight=70, tag='beastkin', role_job='선봉', bag=4,
                          apt=dict(melee=5, spear=1, bow=0, gun=0, magic=2, stealth=1), portrait='@codex:img/char/regina_art.webp', codex='regina',
                          desc='9층의 보스. 알현실에 유폐되어 권태로운 수인 검사 (5성). 에너지계 검술 — 붉게 빛나는 장검'),
    S=dict(A='레지나페흐토테이론/레지나 8프레임 검술 스프라이트', B='레지나페흐토테이론/레지나의 10종 특수 검격', C='레지나페흐토테이론/붉은 검의 여성 보스 8프레임 스프라이트'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', W4)], run=[('A', ['r1c0', 'r1c1'])], kneel=[('A', ['r1c2'])], down=[('A', ['r1c3'])], windup=[('B', ['r0c0'])], thrust=[('B', ['r0c1'])], low=[('B', ['r0c2'])],
           upper=[('B', ['r0c3'])], whirl=[('B', ['r0c4'])], attack=[('B', ['r1c0'])], thrust2=[('B', ['r1c1'])], guard=[('B', ['r1c2'])], crouch=[('B', ['r1c3'])], special=[('B', ['r1c4'])],
           walk2=[('C', W4)]),
    refs=dict(A=[('r0c0', 1.0)], C=[('r0c0', 1.0)], B=[('r1c2', 1.0)])),
  'pehto': dict(new=dict(name='페흐토', rank='5성', role='적', tall=2.0, weight=85, tag='demon', role_job='선봉', bag=4,
                         apt=dict(melee=5, spear=1, bow=0, gun=0, magic=2, stealth=1), portrait='@codex:img/char/pehto_art.webp', codex='pehto',
                         desc='떠돌이 마족 (5성 · 대귀족급). 4층 이후 · 인카운터에 나옴. 인연이 이어지면 영입, 원하면 싸움'),
    S=dict(A='레지나페흐토테이론/등을 보인 기사 8종 스프라이트 시트', B='레지나페흐토테이론/뿔 달린 기사 보스 8종 모션 시트', C='레지나페흐토테이론/뿔 달린 기사 보스 8프레임 스프라이트 시트',
           D='레지나페흐토테이론/뿔 달린 기사 보스의 8가지 강공격'),
    idle=('B', 'r0c0'),
    P=dict(walk=[('C', W4)], walkB=[('A', W4)], run=[('C', ['r1c0', 'r1c1'])], kneel=[('C', ['r1c2'])], down=[('C', ['r1c3'])], dash=[('B', ['r0c1'])], hurt=[('B', ['r0c2'])],
           jump=[('B', ['r0c3'])], lift=[('B', ['r1c0'])], ready=[('B', ['r1c1'])], slam=[('B', ['r1c2'])], guard=[('B', ['r1c3'])], windup=[('D', ['r0c0'])], low=[('D', ['r0c1'])],
           lunge=[('D', ['r0c2'])], sweep=[('D', ['r0c3'])], upper=[('D', ['r1c0'])], leap=[('D', ['r1c1'])], attack=[('D', ['r1c2'])], attack2=[('D', ['r1c3'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 1.0)], C=[('r0c0', 1.0)], D=[('r1c2', 0.95)])),
  'teiron': dict(new=dict(name='테이론', rank='7성', role='보스', tall=2.3, weight=110, tag='demon', role_job='선봉', bag=6,
                          apt=dict(melee=5, spear=5, bow=0, gun=0, magic=2, stealth=0), portrait='@codex:img/char/balyong_art.webp', codex='balyong',
                          desc='작은 우주차원을 호령하던 초승달 왕 (7성). 20층 이후의 강보스 — 하얀 공간이 우주로 침식됨. 대검 레이저 · 극강 투창 · 공간 절단'),
    S=dict(A='레지나페흐토테이론/초승달 왕의 8가지 전투 자세', B='레지나페흐토테이론/타이론 후방 3_4 보행 스프라이트 시트', C='레지나페흐토테이론/타이론의 9컷 전투 스프라이트', D='레지나페흐토테이론/테이론 대검스킬 5종'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('C', W4)], walkB=[('B', W4)], run=[('C', ['r1c0'])], low=[('C', ['r1c1'])], thrust=[('C', ['r1c2'])], windup=[('C', ['r2c0'])], sweep=[('C', ['r2c1'])],
           spear=[('A', ['r0c1'])], cross=[('A', ['r0c2'])], leap=[('A', ['r0c3'])], kneel=[('A', ['r1c0'])], guard=[('A', ['r1c1'])], whirl=[('A', ['r1c2'])], idle2=[('A', ['r1c3'])],
           gs_swing=[('D', ['r0c0'])], gs_raise=[('D', ['r0c1'])], gs_slam=[('D', ['r0c2'])], gs_thrust=[('D', ['r1c0'])], gs_guard=[('D', ['r1c1'])], down=[('B', ['r1c1'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 1.0)], C=[('r0c0', 1.0)], D=[('r1c1', 0.9)])),
  'chinchilla': dict(new=dict(name='친칠라', rank='4성', role='동료', tall=1.6, weight=50, tag='beastkin', role_job='사수', bag=3,
                              apt=dict(melee=1, spear=0, bow=5, gun=1, magic=0, stealth=3), portrait='@codex:img/char/chinchilla_art.webp', codex='chinchilla',
                              desc='심해 종족의 궁수 (4성). 홀로 떨어져 주운 장비로 사냥하며 잘 적응함 — 이곳도 하나의 심해라고 여김'),
    S=dict(A='친칠라추가/곰 후드 청록 궁수 5포즈 시트', B='친칠라추가/곰 후드 청색 궁수의 다섯 포즈', C='친칠라추가/아이보리 활을 든 다섯 친칠라', D='친칠라추가/치치닐라 궁수의 다섯 가지 일상 자세, 사과는 삭제',
           E='친칠라추가/친칠라 궁수 10종 동작 스프라이트 시트 사과같은 특정 스프라이트는 모두 제거해서 사용(다른데서도 쓰게', F='친칠라추가/친칠라의 다섯 가지 일상 포즈', G='친칠라추가/푸른 궁수의 여덟 가지 스킬 포즈'),
    idle=('D', 'r0c2'),
    P=dict(walk=[('E', W4)], run=[('E', ['r0c4', 'r1c0'])], hurt=[('E', ['r1c1'])], down=[('E', ['r1c2'])], rest=[('E', ['r1c3'])], kneel=[('E', ['r1c4'])],
           aim=[('G', ['r0c0'])], multishot=[('G', ['r0c1'])], kneelshot=[('G', ['r0c2'])], twist=[('G', ['r0c3'])], low=[('G', ['r1c0'])], skyshot=[('G', ['r1c1'])], attack=[('G', ['r1c2'])], shoot=[('G', ['r1c3'])],
           leap=[('A', ['r1c0'])], crouch=[('A', ['r1c1'])], sit=[('D', ['r0c1'])], read=[('D', ['r1c0'])], stretch=[('F', ['r0c1'])], tea=[('F', ['r1c0'])]),
    refs=dict(D=[('r0c2', 1.0)], E=[('r0c0', 0.98)], G=[('r1c3', 1.0)], A=[('r0c0', 1.0)], F=[('r0c1', 1.05)]), sk=dict(G=0.87, A=0.92)),
  'traka': dict(new=dict(name='트라카', rank='1성', role='동료', tall=1.35, weight=40, tag='goblin', role_job='사수', bag=2,
                         apt=dict(melee=2, spear=0, bow=4, gun=0, magic=1, stealth=3), portrait='@codex:img/char/traka_art.webp', codex='traka',
                         desc='고블린 궁수 (1성). 청광묵과 동향이지만 모르는 사이, 발화 능력은 더 약함. 주워 주면 좋아함'),
    S=dict(A='추가스프라이트/트라카 9프레임 동작 스프라이트 시트', B='추가스프라이트/트라카의 여덟 가지 활 공격'),
    idle=('A', 'r0c0'),
    P=dict(walk=[('A', W4)], run=[('A', ['r1c0', 'r1c1'])], down=[('A', ['r2c0'])], kick=[('A', ['r2c2'])], hurt=[('A', ['r2c3'])], aim=[('B', ['r0c0'])], shoot=[('B', ['r0c1'])],
           kneelshot=[('B', ['r0c2'])], crouch=[('B', ['r0c3'])], low=[('B', ['r1c0'])], leapshot=[('B', ['r1c1'])], draw=[('B', ['r1c2'])], prone=[('B', ['r1c3'])]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 1.0)])),
  # ───────── 있던 2 · 3기 인물 덧붙임 ─────────
  'manghyang': dict(S=dict(A='망향추가/다섯 포즈 완성형 캐릭터 시트', B='망향추가/망향 악마 전사의 10포즈 스프라이트 (1)', D='망향추가/망향 악마 전투 포즈 스프라이트 시트',
                           E='망향추가/분홍 머리 뿔 여전사 10포즈 스프라이트 시트', F='망향추가/분홍 장발 뿔 전사 5포즈 스프라이트'),
    P=dict(walk=[('B', W5)], run=[('B', ['r1c0', 'r1c1'])], windup=[('B', ['r1c2'])], attack=[('B', ['r1c3'])], attack2=[('B', ['r1c4'])], ready=[('D', ['r0c2'])], low=[('D', ['r1c0'])],
           hurt=[('E', ['r0c2'])], down=[('E', ['r0c3'])], kneel=[('E', ['r0c4'])], rest=[('E', ['r1c0'])], rest2=[('E', ['r1c1'])], idle2=[('E', ['r0c0'])],
           guard=[('F', ['r0c0'])], kick=[('F', ['r0c1'])], lift=[('F', ['r0c2'])], dash=[('F', ['r1c0'])], claw=[('F', ['r1c1'])], sit=[('A', ['r1c1'])], carry=[('A', ['r0c0'])]),
    refs=dict(B=[('r0c0', 0.98)], D=[('r0c0', 1.0)], E=[('r1c2', 1.0)], F=[('r1c1', 0.95)], A=[('r1c0', 1.0)]), sk=dict(E=0.9, F=0.9, A=0.87)),
  'magusgirl': dict(S=dict(A='마도사녀추가/붉은 머리 뿔마녀 9종 액션 스프라이트', B='마도사녀추가/뿔 달린 마법사 10프레임 포즈 시트', C='마도사녀추가/뿔 달린 마법사 전투 스프라이트 10종'),
    P=dict(walk=[('B', W5)], run=[('B', ['r1c0', 'r1c1'])], windup=[('B', ['r1c2'])], attack=[('B', ['r1c3'])], attack2=[('B', ['r1c4'])], attackB=[('A', ['r0c1'])], hurt=[('A', ['r0c2'])],
           down=[('A', ['r0c3'])], kneel=[('A', ['r0c4'])], rest=[('A', ['r1c0'])], ready=[('A', ['r1c2'])], jump=[('A', ['r1c3'])], walk2=[('C', W5)]),
    refs=dict(A=[('r0c0', 1.0)], B=[('r0c0', 1.0)], C=[('r0c0', 1.0)])),
  'stagbeast': dict(S=dict(A='추가스프라이트/사슴 해골 영웅 10종 동작 스프라이트', B='추가스프라이트/사슴 해골 영웅 10종 스프라이트', C='추가스프라이트/사슴 해골 영웅의 전투 스프라이트', D='추가스프라이트/사슴 해골 전사의 레슬링 포즈 8종'),
    P=dict(walk=[('A', W5)], run=[('A', ['r1c0', 'r1c1'])], windup=[('A', ['r1c2'])], attack=[('A', ['r1c3'])], attack2=[('A', ['r1c4'])], ready=[('B', ['r0c0'])], grab=[('B', ['r0c1'])],
           hurt=[('B', ['r0c2'])], down=[('B', ['r0c3'])], kneel=[('B', ['r0c4'])], rest=[('B', ['r1c1'])], guard=[('B', ['r1c2'])], jump=[('B', ['r1c4'])],
           punch=[('C', ['r0c0', 'r0c1'])], kick=[('C', ['r1c0'])], kick2=[('C', ['r1c1'])], stance=[('D', ['r0c0'])], flex=[('D', ['r0c3'])], crawl=[('D', ['r1c1'])], pound=[('D', ['r1c2'])]),
    refs=dict(A=[('r0c0', 0.98)], B=[('r0c2', 0.92)], C=[('r0c2', 0.95)], D=[('r0c1', 1.0)])),
  'inclador': dict(S=dict(A='장끌레도르추가/회전 망치 워킹 스프라이트 시트', B='장끌레도르추가/상승과 하강의 해머 강타', C='장끌레도르추가/금발 남자의 더블 해머 스매시', D='장끌레도르추가/금발 남성의 두 가지 해머 공격'),
    P=dict(walk=[('A', ['r0c0', 'r0c1', 'r1c0', 'r1c1'])], walkB=[('A', ['r0c2', 'r0c3', 'r1c2', 'r1c3'])], windup=[('B', ['r0c0'])], attack=[('B', ['r0c1'])], attackB=[('C', ['r0c0'])],
           smash=[('D', ['r0c1'])]),
    refs=dict(A=[('r0c0', 0.98)], B=[('r0c0', 0.95)], C=[('r0c0', 0.8)], D=[('r0c1', 0.75)]), sk=dict(B=0.82, C=0.82, D=0.83),
    A=dict(upper=('장끌레도르추가/장도리 스킬 - 어퍼.webp', 17, 33, 9, 'fix', dict(fps=14, once=1)),
           liver=('장끌레도르추가/장도리 리버샷.webp', 17, 33, 9, 'fix', dict(fps=14, once=1)),
           noir=('장끌레도르추가/느와르 장도리 어퍼.webp', 17, 33, 9, 'fix', dict(fps=14, once=1)),
           headsmash=('장끌레도르추가/장도리 스킬 - 내려찍기.webp', 30, 50, 9, 'fix', dict(fps=13, once=1)),
           execute=('장끌레도르추가/필살 치명타 내려찍기 장도리.webp', 38, 51, 8, 'fix', dict(fps=12, once=1))),
    aref=(0, 0.98)),
  'pearl': dict(S={}, P={},
    A=dict(idle=('펄추가/서서대기펄.webp', 0, 19, 10, 'fix', dict(fps=6)),
           fly=('펄추가/날펄대기.webp', 0, 15, 8, 'fix', dict(fps=7)),
           attack=('펄추가/찍고빼기.webp', 0, 22, 7, 'fix', dict(fps=12, once=1)),
           throw=('펄추가/신펄 정면투창.webp', 0, 14, 7, 'fix', dict(fps=10, once=1)),
           spin=('펄추가/신펄 반경 3m원형베기.webp', 0, 22, 8, 'track', dict(fps=12, once=1)),
           skythrow=('펄추가/신펄 공중투창.webp', 0, 12, 6, 'fix', dict(fps=9, once=1)),
           execute=('펄추가/정면처형.webp', 0, 20, 7, 'track', dict(fps=12, once=1)),
           kick=('펄추가/바로 돌려차기.webp', 24, 57, 8, 'track', dict(fps=12, once=1)),
           upper=('펄추가/펄 어퍼.webp', 0, 33, 8, 'fix', dict(fps=12, once=1)),
           slash=('펄추가/펄 사선베기.webp', 0, 18, 7, 'track', dict(fps=12, once=1)),
           twirl=('펄추가/창돌리는펄.webp', 0, 30, 8, 'fix', dict(fps=10, once=1)),
           chop=('펄추가/찍기펄.webp', 0, 21, 7, 'fix', dict(fps=11, once=1))),
    scale_by='idle', ak=dict(fly=0.9, skythrow=1.22, upper=1.08)),
  'pearlgak': dict(new=dict(name='각펄', rank='2성', role='보스', tall=1.58, weight=48, tag='angel', role_job='선봉', bag=3,
                            apt=dict(melee=5, spear=5, bow=0, gun=0, magic=3, stealth=1), portrait=None, codex='h2_pearl', idle_from='pearl',
                            desc='보스 인카운터로 나온 펄 (각펄, 2성). «펄이 이렇게나 강해?» 가 아니라 «이게 2성이구나!» 를 보여 주는 판 — 능력치는 2성 그대로, 기술을 끝까지 다 씀. 호러에 가까운 연출. 정면투창 · 공중투창 (창비 · 거대 창) · 처형 · 연속 찌르기 · 넓은 횡베기 · 땅에서 솟는 거대 창'),
    S={}, P={},
    A=dict(idle=('펄추가/서서대기펄.webp', 0, 19, 10, 'fix', dict(fps=6)),
           attack=('펄추가/각펄 찍고빼기.webp', 0, 22, 7, 'fix', dict(fps=12, once=1)),
           throw=('펄추가/각펄 정면투창.webp', 0, 16, 7, 'fix', dict(fps=10, once=1)),
           wide=('펄추가/각펄 반경 10m원형베기.webp', 0, 24, 8, 'track', dict(fps=12, once=1)),
           skythrow=('펄추가/각펄 공중투창.webp', 0, 14, 6, 'fix', dict(fps=9, once=1)),
           bigthrow=('펄추가/각펄 곤중투창2 초대형치명타.webp', 0, 14, 6, 'fix', dict(fps=9, once=1)),
           execute=('펄추가/각펄 정면처형.webp', 0, 20, 7, 'track', dict(fps=12, once=1)),
           triple=('펄추가/각벌 3번 연속 베기.webp', 0, 33, 10, 'track', dict(fps=13, once=1)),
           pillar=('펄추가/각펄스킬.webp', 0, 19, 8, 'fix', dict(fps=9, once=1)),
           plunge=('펄추가/처형 펄.webp', 4, 27, 8, 'fix', dict(fps=10, once=1)),
           flythrow=('펄추가/각펄 날아투창.webp', 0, 27, 8, 'track', dict(fps=11, once=1)),
           stepthrust=('펄추가/pearl_stepthrust_gak_v1.webp', 0, 19, 8, 'track', dict(fps=12, once=1)),
           cannon=('펄추가/pearl_cannon_gak_v1.webp', 0, 20, 8, 'track', dict(fps=12, once=1))),
    scale_by='idle', ak=dict(throw=1.05, skythrow=1.25, bigthrow=1.25, execute=1.1, pillar=1.55, plunge=1.3, cannon=1.1)),
}
# 세르파 소환물 (원화 한 장 → 서 있는 그림 하나, 노트만): 파일, (두 사람이면 왼쪽 0 / 오른쪽 1), 노트
SUMMONS = {
  'gula': ('세르파/굴라 - 검사, 튤린 - 서폿.png', 0, dict(name='굴라', tall=1.75, weight=70, role_job='선봉', desc='세르파 소환 · 검사 (마도공학 기사)')),
  'tulin': ('세르파/굴라 - 검사, 튤린 - 서폿.png', 1, dict(name='튤린', tall=1.65, weight=55, role_job='치유', desc='세르파 소환 · 서포터')),
  'pin': ('세르파/핀 - 세르파소환 사수.png', None, dict(name='핀', tall=1.7, weight=55, role_job='사수', desc='세르파 소환 · 사수 (긴 총)')),
  'mong': ('세르파/방패명 - 몽.png', None, dict(name='몽', tall=1.9, weight=140, role_job='방패', desc='세르파 소환 · 방패 (큰 수정 방패)')),
  'maidA': ('세르파/일반 시종A.png', None, dict(name='일반 시종 A', tall=1.7, weight=55, role_job='선봉', desc='세르파 소환 · 시종')),
  'maidB': ('세르파/일반시종 B.png', None, dict(name='일반 시종 B', tall=1.7, weight=60, role_job='선봉', desc='세르파 소환 · 시종 (광석 알 든 앞치마)')),
  'unitFight': ('세르파/일반전투유닛.png', None, dict(name='일반 전투 유닛', tall=1.1, weight=120, role_job='돌격', desc='세르파 소환 · 광석 짐승 (근접)', wide=1)),
  'unitTank': ('세르파/일반탱킹유닛.png', None, dict(name='일반 탱킹 유닛', tall=1.4, weight=300, role_job='방패', desc='세르파 소환 · 광석 짐승 (몸빵)', wide=1)),
  'unitMid': ('세르파/고급 마도유닛 중거리.png', None, dict(name='고급 마도 유닛', tall=1.9, weight=90, role_job='마법', desc='세르파 소환 · 마도공학 유닛 (중거리)')),
  'crab': ('4기 누락 부인, 보라거인, 리완 추가/crystal_bubble_crab_v1.png', None, dict(name='수정 거품게', tall=0.55, weight=12, role_job='자원', desc='세르파의 자원 유닛 — 저절로 생기고 불어나며 (증식), 세르파가 모아서 유닛을 뽑음 (세르파 로직의 핵심). 싸움은 못 함', wide=1, res=1, outline=1)),
  'unitFar': ('세르파/고급 마도공학 유닛. 결국 작은 슬라임들을 얼마나 모으고 증식시키냐로 유닛 소환 가능, 원거리.png', None, dict(name='고급 마도공학 유닛', tall=1.8, weight=70, role_job='사수', desc='세르파 소환 · 원거리 (작은 슬라임을 모으고 불려 유닛을 부름)')),
}
