# relic_table.py v1.1 — 유물 효과표 (Claude가 지음, 민수가 도감에 적은 spec은 그대로)
# v1.1: 이름 없는 유물 28개에 게임 속 이름 (n) · 효과를 붙임 (도감 이름은 그대로 둠)
# slot: weapon (무기 유물: wt = 무기 종류) / head / body / legs / acc (착용) / carry (가방에 있으면) / use (소모품) / furn (굴 가구) / pet
# fx: rpg.js가 읽는 효과 (아래 키). d: 설명 (툴팁)
# 키: atk atkP def defP hp hpP crit critDmg eva spd vision sanity sanDrain mood regen lifesteal thorns reflectP block shield shieldRegen
#     bleedHit burnHit slowHit shockHit gold goldPick carry arrowCap ammoCap poisonImmune fireImmune shockImmune radar stairs floorMap
#     seaAtk holy summon laser revive escape unlock serum perm skillCd magic fist backstab gunP lootPlus trapSense keySave mark rally
#     knockImmune weight drownImmune str dex vit wil per

R = {
 'O-player-weapon': dict(slot='weapon', wt='spear', rar=3, atk=2, fx=dict(seaAtk=30, holy=30), d='인주가 떨어진 구덩이에서 주운 창. <축복: 바다> 물 · 비 층에서 공격 +30. <특공: 신성> 신 계열 적에게 고정 피해 +30. 투창이 완벽하면 꿰뚫음'),
 'R-A': dict(slot='acc', rar=3, fx=dict(spd=8, eva=5), d='<가호: 바람> 이동 +8%, 회피 +5%. 어린 태자가 자유롭고 안전하길 바랐던 누군가의 염원'),
 'R-B': dict(slot='acc', rar=3, fx=dict(def_=10), d='<가호: 바다> 방어 +10. 바다의 사랑을 받은 나그네의 반지'),
 'R01': dict(slot='carry', rar=5, fx=dict(atk=40), d='공격 +40. 누구의 목을 그었는지는 아무도 말하지 않는다'),
 'R02': dict(slot='carry', rar=3, fx=dict(atk=20), d='이래 봬도 운철석을 가공한 것. 공격 +20'),
 'R03': dict(slot='carry', rar=2, fx=dict(vision=30), d='소지하면 시야 +30%. 어두운 곳에서 특히 좋음'),
 'R07': dict(slot='carry', rar=6, fx=dict(atk=100, eva=10), d='<축복: 오딜> 공격 +100, 회피 +10%. 오딜과 세 번 만나면 선물로 줌'),
 'R10': dict(slot='use', rar=1, fx=dict(unlock=1), d='잠긴 문 · 상자를 한 번 강제로 엶. 소모품'),
 'R11': dict(slot='acc', rar=5, fx=dict(summon='skeleton'), d='착용하면 스킬 "해골병사": 싸움이 시작되면 해골병사 다섯이 일어남 (쓰러져도 다시 일어남)'),
 'R16': dict(slot='carry', rar=3, fx=dict(eva=5, regen=1), d='소지하면 회피 +5%, 초당 체력 +1'),
 'R19': dict(slot='carry', rar=2, fx=dict(sanDrain=-20), d='정신도가 덜 줆 (-20%). 누가 쓴 부적인지 글씨가 번져 있다'),
 'R24': dict(slot='carry', rar=1, fx=dict(mood=10, sanity=5), d='굴의 무드 +10, 정신도 +5. 거울 속 얼굴이 가끔 늦게 웃는다'),
 'R27': dict(slot='furn', rar=2, fx=dict(mood=8), d='설치 가구. 전시해 놓으면 마음이 편해짐 (무드 +8)'),
 'R29': dict(slot='furn', rar=3, fx=dict(mood=12), d='설치 가구. 태엽을 감으면 왕실의 노래 (무드 +12)'),
 'R35': dict(slot='weapon', wt='shotgun', rar=4, atk=4, fx=dict(knock=1), d='나팔총: 산탄 아홉 발, 크게 밀쳐 냄. 장전이 느림'),
 'R-S003': dict(slot='carry', rar=3, fx=dict(bleedBonus=25), d='출혈 중인 적에게 피해 +25%'),
 'R-S004': dict(slot='acc', rar=3, fx=dict(fist=50), d='주먹 · 밀치기 피해 +50%. 맨손이 무기가 됨'),
 'R-S006': dict(slot='weapon', wt='shield', rar=4, atk=2, fx=dict(block=15, set_='wolf'), d='늑대 기사단의 방패. 막기 +15%. 늑대 문장 흉갑과 함께면 사기 +'),
 'R-S007': dict(slot='carry', rar=3, fx=dict(magic=30, wil=3), d='지팡이 마력탄 +30%, 정신 +3'),
 'R-S011': dict(slot='weapon', wt='greatsword', rar=4, atk=20, fx=dict(burnHit=dict(ch=1, pct=3, dur=5)), d='강해 보이지만 굴에선 흔한 물건. 공격 +20, 화상 (초당 최대 체력의 3%, 5초)'),
 'R-S012': dict(slot='body', rar=4, def_=14, fx=dict(thornsBleed=dict(dps=10, dur=3)), d='맞을 때마다 상대에게 출혈 (초당 10, 3초)'),
 'R-S027': dict(slot='weapon', wt='pistol', rar=5, atk=10, fx=dict(laser=3), d='원정마다 세 발. 관통 레이저'),
 'R-S028': dict(slot='head', rar=3, def_=3, fx=dict(sanDrain=-30, mood=-5), d='꿰맨 가죽 가면. 공포를 덜 느낌 (정신도 감소 -30%). 굴에선 다들 쳐다봄 (무드 -5)'),
 'R-S031': dict(slot='body', rar=4, def_=18, fx=dict(set_='wolf'), d='늑대 기사단의 흉갑. 방어 +18'),
 'R-S038': dict(slot='carry', rar=2, fx=dict(stairs=1), d='층에 들어서면 계단 방향을 가리킴'),
 'R-S039': dict(slot='carry', rar=3, fx=dict(enemyInfo=1, sanity=-10), d='적의 체력 · 세기가 보임. 정신도 -10 (읽지 말았어야 했다)'),
 'R-S040': dict(slot='carry', rar=4, fx=dict(shield=100, shieldRegen=2), d='푸른 체력 +100, 초당 2씩 다시 참'),
 'R-S041': dict(slot='acc', rar=3, fx=dict(str=4, reload=20), d='기계 팔. 힘 +4, 재장전 20% 빠름'),
 'R-S042': dict(slot='body', rar=4, def_=25, fx=dict(regen=1, sanity=-15), d='살덩이 기계 흉갑. 방어 +25, 초당 체력 +1. 숨을 쉰다 (정신도 -15)'),
 'R-S044': dict(slot='acc', rar=3, fx=dict(gunP=15), d='총기 피해 +15%'),
 'R-S045': dict(slot='acc', rar=3, fx=dict(lifesteal=5), d='흡혈 +5%'),
 'R-S047': dict(slot='carry', rar=2, fx=dict(drownImmune=1, wetVision=40), d='물 · 비 층에서 시야 +40%, 물에 빠져도 숨 쉼'),
 'R-S050': dict(slot='carry', rar=3, fx=dict(crit=15), d='소지하면 치명 +15%'),
 'R-S058': dict(slot='carry', rar=3, fx=dict(mark=15), d='기계 매. 싸움이 시작되면 가장 강한 적에게 표식 (받는 피해 +15%)'),
 'R-S059': dict(slot='acc', rar=3, fx=dict(vision=25), d='보관된 눈알. 시야 +25%'),
 'R-S060': dict(slot='acc', rar=3, fx=dict(backstab=40), d='그림자 건틀릿. 등 뒤 공격 피해 +40%'),
 'R-S061': dict(slot='use', rar=4, fx=dict(serum=dict(spd=10, hpP=30, atkP=50, dur=30)), d='30초 동안 이동 +10%, 체력 +30%, 공격 +50%. 푸른 아우라. 소모품'),
 'R-S062': dict(slot='use', rar=4, fx=dict(escape=1), d='딱 한 번, 그 자리에서 굴로 돌아감 (가방 그대로). 소모품'),
 'R-S063': dict(slot='body', rar=3, def_=8, fx=dict(defP=10, spd=-5), d='무슨 가죽인지는 모른다. 방어 +10%, 이동 -5%'),
 'R-S065': dict(slot='head', rar=4, def_=6, fx=dict(atkP=30, sanity=-20), d='<저주: 고행> 공격 +30%, 정신도 -20 (쓰고 있는 동안)'),
 'R-S073': dict(slot='use', rar=5, fx=dict(perm=dict(def_=10, atk=10, eva=3, crit=3)), d='마시면 영구히 방어 +10, 공격 +10, 회피 +3%, 치명 +3%'),
 'R-S075': dict(slot='carry', rar=3, fx=dict(floorMap=1), d='층에 들어서면 방들의 자리가 지도에 보임'),
 'R-S076': dict(slot='acc', rar=3, fx=dict(weight=100, spd=-5, knockImmune=1), d='착용하면 무게 +100kg (밀리지 않음), 이동 -5%'),
 'R-S079': dict(slot='acc', rar=3, fx=dict(seaAtkP=20, shockImmune=1), d='아틀란티스 건틀릿. 물 · 비 층 공격 +20%, 감전 면역'),
 'R-S080': dict(slot='carry', rar=3, fx=dict(luck=10), d='점성술 원반. 낙하 · 상자에서 한 등급 좋은 것이 나올 확률 +10%'),
 'R-S082': dict(slot='carry', rar=5, fx=dict(revive=50), d='용의 심장 주머니. 원정마다 한 번, 쓰러지면 체력 50%로 다시 일어남'),
 'R-S083': dict(slot='weapon', wt='axe', rar=6, atk=12, fx=dict(bleedHit=dict(ch=0.5, dps=8, dur=4), boomerang=1), d='도끼기사의 도끼. 출혈 (50%), 던지면 손으로 돌아옴'),
 'R-E01': dict(slot='weapon', wt='sword', rar=5, atk=8, fx=dict(swordWave=1), d='현자의 검. 세 번째 베기마다 검기가 날아감'),
 'R-E02': dict(slot='weapon', wt='sword', rar=6, atk=14, fx=dict(swordWave=2, crit=10), d='오닐의 검 (히든). 모든 베기에 검기, 치명 +10%'),
 'R-E03': dict(slot='carry', rar=4, fx=dict(sanity=10, sell=300), d='어떤 보석. 들여다보면 마음이 가라앉음 (정신도 +10). 비싸게 팔림'),
 'R-E04': dict(slot='pet', rar=5, fx=dict(pet='witchfairy'), d='펫: 꼬마마녀요정. 따라다니며 별가루로 적을 느리게 함'),
 'R-E05': dict(slot='pet', rar=5, fx=dict(pet='blackrabbit'), d='펫: 흑토끼기사. 따라다니며 작은 칼로 싸움'),
 'R-E06': dict(slot='carry', rar=6, fx=dict(revive=100, reviveBurn=1), d='불타는 하트. 원정마다 한 번, 쓰러지면 불꽃 속에서 일어남 (주변 화상)'),
 'R-S084': dict(slot='weapon', wt='dagger', rar=3, atk=3, fx=dict(bleedHit=dict(ch=0.3, dps=6, dur=4)), d='구멍 뚫린 피 묻은 칼. 출혈 30%'),
 'R-S086': dict(slot='legs', rar=3, def_=1, fx=dict(spd=10, eva=5, trapDmg=50), d='붉은 유리 하이힐. 이동 +10%, 회피 +5%. 함정 피해 +50%'),
 'R-S087': dict(slot='carry', rar=3, fx=dict(trapSense=1), d='수저 다리 기계 거미. 함정이 보이고 해제가 쉬워짐'),
 'R-S088': dict(slot='weapon', wt='crossbow', rar=4, atk=8, fx=dict(pierce=1), d='상아 개머리 석궁. 볼트가 꿰뚫음'),
 'R-S090': dict(slot='acc', rar=2, fx=dict(crit=5), d='끈 달린 비취 곡옥 부적. 치명 +5%'),
 'R-S091': dict(slot='carry', rar=2, fx=dict(keySave=50), d='열쇠를 쓸 때 50%는 부러지지 않음'),
 'R-S093': dict(slot='carry', rar=3, fx=dict(drill=1), d='수동 드릴. 잠긴 문 · 상자를 열쇠 없이 뚫음 (시간이 걸리고 시끄러움)'),
 'R-S094': dict(slot='furn', rar=2, fx=dict(mood=6), d='나비 표본. 굴에 걸면 무드 +6'),
 'R-S095': dict(slot='acc', rar=3, fx=dict(fist=30, bleedHit=dict(ch=0.2, dps=4, dur=3)), d='칼날 달린 가시 너클. 주먹 피해 +30%, 출혈 20%'),
 'R-S096': dict(slot='carry', rar=4, fx=dict(rally=8), d='체스 여왕 주머니. 동료 모두 공격 +8%'),
 'R-S097': dict(slot='carry', rar=1, fx=dict(per=2, lore=1), d='깨진 돌알 속 낡은 쪽지. 감각 +2 (쪽지를 읽으면 이야기)'),
 'R-S098': dict(slot='carry', rar=3, fx=dict(hookCrit=1), d='붕대 감긴 녹슨 갈고리. 치명타가 적을 끌어당김'),
 'R-S099': dict(slot='carry', rar=4, fx=dict(atkP=20, nightSan=10), d='<저주> 검은 가시 쇠 책. 공격 +20%, 매일 밤 정신도 -10'),
 'R-S100': dict(slot='acc', rar=3, fx=dict(per=4, rangedCrit=8), d='호박색 겹렌즈. 감각 +4, 원거리 치명 +8%'),
 'R-S102': dict(slot='carry', rar=4, fx=dict(potionFloor=1, sanity=-5), d='거미 다리 도자기 병. 층마다 물약 하나를 낳음. 정신도 -5'),
 'R-S103': dict(slot='carry', rar=4, fx=dict(sealed=10), d='밀랍 봉인된 검은 철함. 열 방법이 없다… 원정을 열 번 함께하면?'),
 'R-S104': dict(slot='carry', rar=3, fx=dict(crit=10, atkP=10), d='붕대 감긴 나무 작살총. 치명 +10%, 공격 +10%'),
 'R-S106': dict(slot='carry', rar=4, fx=dict(radar=1), d='뱅가의 잘린 귀. 어떤 초월자의 귀. 지도에 적이 보임'),
 'R-S107': dict(slot='carry', rar=2, fx=dict(goldPick=5), d='척추뼈 구슬 주판. 금화를 주울 때마다 +5'),
 'R-S108': dict(slot='carry', rar=3, fx=dict(crit=10, bleedHit=dict(ch=0.25, dps=5, dur=5)), d='녹슨 곡선 톱. 치명 +10%, 출혈 (초당 5, 5초)'),
 'R-S109': dict(slot='acc', rar=4, fx=dict(hp=40, fireImmune=1), d='용 비늘 벨트. 체력 +40, 화상 면역'),
 'R-S110': dict(slot='carry', rar=5, fx=dict(deepStairs=1), d='나선 계단이 든 푸른 수정. 계단이 두 층 아래로 이어짐'),
 'R-S111': dict(slot='carry', rar=2, fx=dict(def_=10), d='어느 왕국 기사단장의 문양. 방어 +10'),
 'R-S112': dict(slot='carry', rar=4, fx=dict(redThread=30), d='붉은 실 실패. 동료가 쓰러지면 20초 동안 인주 공격 +30%'),
 'R-S113': dict(slot='carry', rar=2, fx=dict(def_=5, block=10), d='방패 모양 쇠 문고리. 방어 +5, 막기 +10%'),
 'R-S114': dict(slot='carry', rar=4, fx=dict(egg=3, sanDrain=10), d='꿰맨 자국 난 흰 알. 따뜻하다. 무언가 안에서 듣고 있다'),
 'R-S115': dict(slot='carry', rar=2, fx=dict(lootPlus=1), d='쇠 갈퀴. 시체를 뒤지면 하나 더 나옴'),
 'R-S116': dict(slot='carry', rar=3, fx=dict(carry=4), d='송곳니 장식 가방. 가방 칸 +4'),
 'R-S117': dict(slot='carry', rar=2, fx=dict(pick=30), d='톱니 집게. 자물쇠 따기 · 함정 해제 +30%'),
 'R-S118': dict(slot='carry', rar=4, fx=dict(crow=1), d='봉인된 까마귀. 층마다 한 번 다음 방들을 미리 봄'),
 'R-S119': dict(slot='carry', rar=2, fx=dict(poisonImmune=1), d='놋쇠 필터 방독면. 중독 · 가스 면역'),
 'R-S121': dict(slot='carry', rar=3, fx=dict(crit=10), d='사기치다 걸린 전설의 도박사의 최후. 치명 +10%'),
 'R-S122': dict(slot='acc', rar=3, fx=dict(eva=10), d='올리브정령의 반지. 회피 +10%'),
 'R-S124': dict(slot='body', rar=5, def_=15, fx=dict(spd=5, set_='pehto'), d='페흐토의 망토. 방어 +15, 이동 +5%. 페흐토 세트'),
 'R-S125': dict(slot='weapon', wt='sword', rar=5, atk=10, fx=dict(swordWave=1, set_='pehto'), d='페흐토의 장검. 세 번째 베기에 검기. 페흐토 세트'),
 'R-S126': dict(slot='head', rar=5, def_=10, fx=dict(crit=5, set_='pehto'), d='페흐토의 투구. 방어 +10, 치명 +5%. 페흐토 세트 (셋이면 공격 +20%)'),
 'R-S127': dict(slot='body', rar=6, def_=8, fx=dict(wil=5, sanity=20, magic=20, set_='sage'), d='칼의 로브. 정신 +5, 정신도 +20, 마력탄 +20%. 현자 세트'),
 'R-S128': dict(slot='head', rar=6, def_=4, fx=dict(wil=4, skillCd=15, set_='sage'), d='칼의 모자. 정신 +4, 스킬 대기 -15%. 현자 세트'),
 'R-S129': dict(slot='weapon', wt='staff', rar=6, atk=8, fx=dict(magicTriple=1, set_='sage'), d='칼의 완드. 마력탄이 세 갈래로. 현자 세트'),
 'R-S131': dict(slot='acc', rar=4, fx=dict(magic=15, shockHit=dict(ch=0.2, dur=1.2)), d='구리 회로 마법 장갑. 마력탄 +15%, 감전 20%'),
 'R-S132': dict(slot='acc', rar=3, fx=dict(sanDrain=-15, eva=3), d='떨어져나간 부적 파편. 정신도 감소 -15%, 회피 +3%'),
 'R-S133': dict(slot='acc', rar=4, fx=dict(skillCd=10, wil=2), d='마젠타 기억석 오팔 커프. 스킬 대기 -10%, 정신 +2'),
 'R-S134': dict(slot='acc', rar=3, fx=dict(keySave=30), d='보랏빛 봉인편지 열쇠 귀걸이. 열쇠를 쓸 때 30%는 남음'),
 'R-S136': dict(slot='weapon', wt='shield', rar=5, atk=4, fx=dict(defP=20, reflectP=5), d='인디고 렌즈 세라믹 버클러. 방어 +20%, 막은 피해의 5% 되돌림'),
 'R-S137': dict(slot='carry', rar=4, fx=dict(aurora=15), d='오로라 봉인서. 층의 첫 싸움 동안 모두 공격 +15%'),
 'R-S138': dict(slot='weapon', wt='dagger', rar=4, atk=6, fx=dict(critDmg=40), d='호박 균열의 흑유리 단검. 치명 피해 +40%'),
 'R-S005': dict(slot='carry', rar=2, fx=dict(quick=1), d='물약 가방. 소모품 칸 +1'),
 'R-S016': dict(slot='carry', rar=2, fx=dict(carry=3), d='가죽 배낭. 가방 칸 +3'),
 'R-S036': dict(slot='use', rar=2, fx=dict(potions=3), d='물약 병 모음. 열면 물약 셋'),
 'R-S053': dict(slot='carry', rar=3, fx=dict(potionP=30), d='연금술 가방. 물약 효과 +30%'),
 'R-S054': dict(slot='carry', rar=4, fx=dict(curseDoll=20), d='저주 인형. 강적 · 보스는 체력 20%를 잃은 채 시작'),
 'R-S064': dict(slot='acc', rar=3, fx=dict(lifesteal=3, hp=20), d='피 약병 목걸이. 흡혈 +3%, 체력 +20'),
 # v1.1 — 이름 없는 유물 (그림을 보고 지음). n = 게임 속 이름
 'R04': dict(n='은잎 월장석 반지', slot='acc', rar=3, fx=dict(wil=3, sanDrain=-10), d='<가호: 달> 정신 +3, 어둠 속에서 정신도가 덜 줆 (-10%)'),
 'R08': dict(n='받침 위의 눈', slot='carry', rar=3, fx=dict(ambushSense=1, nightSan=3), d='매복 · 미믹을 알아챔. 밤마다 정신도 -3 (눈이 감기지 않는다)'),
 'R09': dict(n='녹슨 왕관 조각', slot='head', rar=4, def_=4, fx=dict(rally=5), d='왕이 없는 왕관. 쓰면 동료가 조금 더 따름 (동료 공격 +5%)'),
 'R12': dict(n='푸른 소용돌이 병', slot='use', rar=3, fx=dict(sanHeal=25, torch=120), d='마시면 정신도 +25, 횃불이 다시 타오름 (+120초). 소모품'),
 'R17': dict(n='소라 귀걸이', slot='acc', rar=2, fx=dict(sanity=8, seaSpd=10), d='바다 소리가 들린다. 정신도 +8, 물 · 비 층에서 이동 +10%'),
 'R21': dict(n='백합 빗', slot='carry', rar=2, fx=dict(mood=6), d='굴의 무드 +6. 레베카가 빗어 달라고 함'),
 'R22': dict(n='놋쇠 나침반', slot='carry', rar=3, fx=dict(stairs=1, ropeDir=1), d='계단과 귀환 줄의 방향을 가리킴'),
 'R23': dict(n='초승달 걸쇠 성서', slot='carry', rar=3, fx=dict(holyP=20, sanity=10), d='읽을 수 없는 글자. 신성 피해 +20%, 정신도 +10'),
 'R25': dict(n='붉은 밀랍 도장', slot='carry', rar=2, fx=dict(shopDisc=10, sell=200), d='누군가의 도장. 상점 값 -10%, 비싸게 팔림'),
 'R26': dict(n='흑단 염주', slot='acc', rar=3, fx=dict(sanDrain=-15, hp=15), d='굴리면 마음이 가라앉는다. 정신도 감소 -15%, 체력 +15'),
 'R28': dict(n='깃털 장식 핀', slot='acc', rar=2, fx=dict(dodgeCd=20), d='가벼운 걸음. 구르기 대기 -20%'),
 'R30': dict(n='초승달 석상', slot='furn', rar=3, fx=dict(mood=5, raidLess=30), d='굴에 두면 밤 습격이 덜 옴 (-30%), 무드 +5'),
 'R31': dict(n='척추 갑주', slot='body', rar=4, def_=16, fx=dict(knockImmune=1, spd=-5), d='등뼈가 이어진 갑주. 방어 +16, 밀리지 않음, 이동 -5%'),
 'R32': dict(n='진자 눈알', slot='carry', rar=4, fx=dict(critMark=15), d='흔들리는 눈알. 치명타를 맞은 적은 3초 동안 받는 피해 +15%'),
 'R33': dict(n='가시 박쥐 우산', slot='weapon', wt='shield', vr='umbrella', rar=4, atk=3, fx=dict(reflectP=10), d='가시 박힌 붉은 우산. 펼치면 화살을 막고, 막을 때 가시가 찌름 (10% 되돌림)'),
 'R34': dict(n='나선 송곳', slot='weapon', wt='dagger', rar=3, atk=2, fx=dict(armorPierce=30), d='꿰뚫는 송곳. 방어 30% 무시'),
 'R36': dict(n='은빛 연꽃', slot='carry', rar=3, fx=dict(restHeal=20), d='시들지 않는 꽃. 모닥불에서 쉬면 체력을 더 되찾음 (+20%)'),
 'R37': dict(n='지네 목줄', slot='acc', rar=4, fx=dict(poisonHit=dict(ch=0.1, dps=6, dur=4)), d='공격할 때 10%로 중독 (초당 6, 4초)'),
 'R38': dict(n='요정 날개 장식', slot='acc', rar=4, fx=dict(eva=5, jump=20), d='날개가 떨린다. 회피 +5%, 점프 +20%'),
 'R40': dict(n='쇠 정육면체', slot='carry', rar=3, fx=dict(sealed=5), d='무거운 쇠 상자 퍼즐. 원정을 다섯 번 함께하면 열림'),
 'R43': dict(n='핏빛 깃발창', slot='weapon', wt='spear', vr='banner', rar=4, atk=4, fx=dict(rally=10), d='찢긴 깃발 달린 창. 들고 있으면 동료 공격 +10%'),
 'R44': dict(n='반달 성벽 방패', slot='weapon', wt='shield', rar=4, atk=2, fx=dict(block=20), d='부채꼴 성벽 방패. 막기 +20%'),
 'R45': dict(n='사슬 낫', slot='weapon', wt='spear', vr='whip', rar=4, atk=4, fx=dict(hookPull=1), d='사슬 달린 낫. 길게 닿고, 맞은 적을 끌어당김'),
 'R46': dict(n='해골 손 건틀릿', slot='acc', rar=4, fx=dict(fist=40, str=3), d='뼈 손가락 건틀릿. 힘 +3, 주먹 피해 +40%'),
 'R47': dict(n='등불 철퇴', slot='weapon', wt='hammer', vr='mace', rar=4, atk=4, fx=dict(vision=20, burnHit=dict(ch=0.15, pct=2, dur=4)), d='등불이 달린 철퇴. 시야 +20%, 화상 15%'),
 'R48': dict(n='순례자의 지팡이', slot='weapon', wt='staff', rar=3, atk=3, fx=dict(sanity=10, holyP=15), d='초가 꽂힌 지팡이. 정신도 +10, 마력탄이 신성 (+15%)'),
 'R49': dict(n='낡은 잠수 투구', slot='head', rar=3, def_=6, fx=dict(drownImmune=1, poisonImmune=1), d='숨이 막히지 않는다. 가스 · 물 면역'),
 'R51': dict(n='십자 묵주', slot='acc', rar=3, fx=dict(holyP=20, sanity=5), d='신 계열 적에게 피해 +20%, 정신도 +5'),
 'R52': dict(n='성상 배낭', slot='carry', rar=4, fx=dict(carry=4, sanity=5), d='성녀상이 든 배낭. 가방 칸 +4, 정신도 +5'),
 'R53': dict(n='가시 견갑', slot='body', rar=3, def_=10, fx=dict(thorns=8), d='가시 박힌 견갑. 방어 +10, 때린 적에게 8 되돌림'),
 'R54': dict(n='가시 면류관', slot='head', rar=5, def_=2, fx=dict(atkP=25, regen=-0.5, sanity=-15), d='<저주> 공격 +25%, 피가 흐름 (초당 체력 -0.5), 정신도 -15'),
 'R-S032': dict(n='고문 도구 걸이', slot='furn', rar=2, fx=dict(mood=-8, raidLess=20), d='굴에 걸면 습격이 줄지만 (-20%) 다들 불편해함 (무드 -8)'),
}
